food_app/urls.py
from django.conf.locale import vi
from django.urls import path

from food_app import views

app_name = 'food_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('order/', views.order, name='order'),
    path('account/', views.account, name='account'),
    path('checkout/', views.checkout, name='checkout'),
    path('payment_confirmation/', views.payment_confirmation, name='payment_confirmation'),
    path('get_plan_price/', views.get_plan_price, name='get_plan_price'),
]

food_plan/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('food_app.urls', namespace='food_app')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foodplan_service/foodplan/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

food_app/forms.py
from django import forms
from django.core.exceptions import ObjectDoesNotExist
from django.forms import widgets

from food_app.models import Plan, PlanPeriod, Promocode, RecipeCategory


class RecipeCategoryRadioSelect(widgets.RadioSelect):
    template_name = 'food_app/partials/recipe_radio_select.html'

    def create_option(self, name, value, label, selected, index, subindex=None, attrs=None):
        option = super().create_option(name, value, label, selected, index, subindex, attrs)
        if value:
            option['attrs']['image'] = value.instance.image.url
            option['attrs']['name'] = value.instance.name
        return option


class OrderForm(forms.ModelForm):
    promo_code = forms.CharField(
        required=False,
        label='Промокод',
        widget=forms.TextInput(attrs={'class': 'form-control me-2', 'placeholder': 'Промокод'}),
    )

    class Meta:
        model = Plan
        fields = ['persons', 'period', 'allergies', 'food_intakes', 'recipe_category', 'promo_code']
        widgets = {
            'recipe_category': RecipeCategoryRadioSelect(
                attrs={'class': 'foodplan_selected d-none'}
            ),
            'food_intakes': forms.CheckboxSelectMultiple(
                attrs={'class': 'form-check-input me-1 foodplan_checked-green'},
            ),
            'allergies': forms.CheckboxSelectMultiple(
                attrs={'class': 'form-check-input me-1 foodplan_checked-green'},
            ),
            'period': forms.Select(attrs={'class': 'form-select'}),
            'persons': forms.Select(attrs={'class': 'form-select'}),
        }

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)

        periods = PlanPeriod.objects.order_by('duration')

        self.fields['period'].initial = periods.first()

        self.fields['recipe_category'].empty_label = None
        self.fields['period'].empty_label = None
        self.fields['food_intakes'].empty_label = None

        self.fields['allergies'].required = False

        self.fields['promo_code'].label_attrs = {'class': 'form-label me-2-label me-2'}

    def clean(self):
        cleaned_data = super().clean()

        promo_code = cleaned_data.get('promo_code')
        if promo_code:
            try:
                promocode = Promocode.objects.get(promocode=promo_code.upper())
                cleaned_data['promo_code'] = promocode
            except ObjectDoesNotExist:
                cleaned_data['promo_code'] = None
        return cleaned_data


class PaymentForm(forms.Form):
    card_name = forms.CharField(min_length=2, label='Имя владельца')
    card_number = forms.CharField(min_length=16, max_length=16, label='Номер карты')
    card_month = forms.IntegerField(min_value=1, max_value=12, label='Месяц')
    card_year = forms.IntegerField(min_value=23, max_value=50, label='Год')
    card_cvc = forms.CharField(min_length=3, max_length=3, label='CVC')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Field attrs
        self.fields['card_name'].widget.attrs.update(
            {
                'class': 'form-control',
                'placeholder': 'Имя Фамилия',
                'type': 'text',
                'id': 'card-name',
                'pattern': '[a-zA-Z ]+',
            }
        )
        self.fields['card_number'].widget.attrs.update(
            {
                'class': 'form-control',
                'placeholder': '1234 5678 9123 4561',
                'type': 'number',
                'id': 'card-number',
                'oninput': 'this.value = this.value.slice(0, 16)',
                'min': '0',
            }
        )
        self.fields['card_month'].widget.attrs.update(
            {
                'class': 'form-control',
                'placeholder': 'MM',
                'type': 'number',
                'id': 'expiry-date-month',
                'pattern': '(0[1-9]|1[0-2])\/[0-9]{2}',
                'oninput': 'this.value = this.value.slice(0, 2)',
            }
        )
        self.fields['card_year'].widget.attrs.update(
            {
                'class': 'form-control',
                'placeholder': 'ГГ',
                'type': 'number',
                'id': 'expiry-date-day',
                'pattern': '(0[1-9]|1[0-2])\/[0-9]{2}',
                'oninput': 'this.value = this.value.slice(0, 2)',
            }
        )
        self.fields['card_cvc'].widget.attrs.update(
            {
                'class': 'form-control',
                'placeholder': '123',
                'type': 'number',
                'id': 'cvc',
                'oninput': 'this.value = this.value.slice(0, 3)',
            }
        )

        # Label attrs
        self.fields['card_name'].label_attrs = {'class': 'form-label'}
        self.fields['card_number'].label_attrs = {'class': 'form-label'}
        self.fields['card_month'].label_attrs = {'class': 'form-label'}
        self.fields['card_year'].label_attrs = {'class': 'form-label'}
        self.fields['card_cvc'].label_attrs = {'class': 'form-label'}

food_app/views.py
import random

from django.db.models import Count, Sum, F
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponseBadRequest, HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect, render
from django.contrib import messages
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt

from yookassa import Payment

from calendar import mdays
from datetime import datetime, timedelta
import uuid

from food_app.forms import OrderForm, PaymentForm
from .models import Customer, Menu, Plan, PlanPeriod, Promocode, Recipe, Subscription


def index(request):
    return render(request, 'food_app/pages/index.html')


@login_required
def account(request):
    if request.method == 'GET':
        customer = Customer.objects.get(user=request.user)
        subscription = Subscription.objects.filter(customer=customer, is_active=True, paid=True)
        if not subscription.exists():
            return render(request, 'food_app/pages/account.html', context={'customer': customer})

        request_date = timezone.now()
        menus = []
        step_counter = 0
        steps_link = []
        calories_list = []
        prices_list = []
        while request_date < timezone.now() + timedelta(days=7):
            item = Menu.objects.filter(
                subscription=subscription.last(), date=request_date
            ).prefetch_related('recipe__ingredients')

            if not item.exists():
                break
            calories_list.append(item.aggregate(calories=Sum('recipe_id__calories')))
            prices_list.append(item.aggregate(prices=Sum('recipe_id__price')))
            menus.append(item)
            steps_link.append(step_counter)
            request_date += timedelta(days=1)
            step_counter += 1
        try:
            date_compare = timezone.now() + timedelta(days=int(request.GET.get('step', 0)))
        except ValueError:
            date_compare = timezone.now()
        calories = calories_list[int(request.GET.get("step", 0))]['calories']
        prices = prices_list[int(request.GET.get("step", 0))]['prices']
        return render(
            request,
            'food_app/pages/account.html',
            context={
                'customer': customer,
                'subscription': subscription.last(),
                'menus': menus,
                'date_compare': date_compare.date(),
                'steps_link': steps_link,
                'calories': calories,
                'prices': prices,
            },
        )

    elif request.method == 'POST':
        user = User.objects.get(pk=request.user.pk)
        user.username = request.POST['username']
        user.email = request.POST['email']
        user.first_name = request.POST['firstname']
        user.last_name = request.POST['lastname']
        user.save()
        if request.FILES:
            customer = Customer.objects.get(user=request.user)
            customer.avatar = request.FILES['avatar']
            customer.save()

        messages.success(request, 'Данные успешно изменены.')

        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def order(request):
    if request.method == 'GET':
        order_form = OrderForm()
        return render(
            request,
            'food_app/pages/order.html',
            {
                'order_form': order_form,
            },
        )

    if request.method == 'POST':
        order_form = OrderForm(request.POST)

        if not order_form.is_valid():
            return render(request, 'food_app/pages/order.html', {'order_form': order_form})

        price = order_form.cleaned_data['period'].price
        promocode = order_form.cleaned_data['promo_code']
        if promocode:
            price = price - price * promocode.discount / 100

        plan = Plan(
            price=price,
            period=order_form.cleaned_data['period'],
            recipe_category=order_form.cleaned_data['recipe_category'],
        )
        plan.save()
        plan.allergies.add(*order_form.cleaned_data['allergies'])
        plan.food_intakes.add(*order_form.cleaned_data['food_intakes'])
        plan.save()

        today = timezone.now()
        print(today)
        subscription_end = today + timedelta(mdays[today.month])
        print(subscription_end)

        subscription = Subscription(
            end=subscription_end,
            plan=plan,
            promocode=promocode if promocode else None,
        )

        subscription.save()
        customer = Customer.objects.get(user=request.user)
        customer.subscriptions.add(subscription)
        customer.save()

        return redirect('food_app:checkout')

    return redirect('food_app:order')


@login_required
def checkout(request):
    subscription = (
        Subscription.objects.filter(customer__user_id=request.user).order_by('-start').first()
    )

    price = subscription.plan.price
    price_without_discount = (
        float(price) / (1 - subscription.promocode.discount / 100)
        if subscription.promocode
        else None
    )

    if request.method == 'POST':
        payment_form = PaymentForm(request.POST)

        if not payment_form.is_valid():
            messages.warning(request, 'Исправьте ошибки в данных карты.')
            return render(
                request,
                'food_app/pages/checkout.html',
                {
                    'payment_form': payment_form,
                    'price': price,
                    'price_without_discount': price_without_discount,
                },
            )

        idempotence_key = str(uuid.uuid4())
        month = str(payment_form.cleaned_data["card_month"])
        payment = Payment.create(
            {
                'amount': {
                    'value': price,
                    'currency': 'RUB',
                },
                'payment_method_data': {
                    'type': 'bank_card',
                    'card': {
                        'number': payment_form.cleaned_data['card_number'],
                        'expiry_year': f'20{payment_form.cleaned_data["card_year"]}',
                        'expiry_month': f'0{month}' if len(month) == 1 else month,
                        'csc': payment_form.cleaned_data["card_cvc"],
                        'cardholder': payment_form.cleaned_data['card_name'],
                    },
                },
                'confirmation': {
                    'type': 'redirect',
                    'return_url': request.build_absolute_uri(
                        reverse('food_app:payment_confirmation')
                    ),
                },
                'metadata': {},
                'capture': True,
                'description': 'Оплата: подписка на сервис FoodPlan',
                'test': True,
            },
            idempotence_key,
        )
        confirmation_url = payment.confirmation.confirmation_url
        request.session['payment_id'] = payment.id
        request.session['subscription_id'] = subscription.id
        return redirect(confirmation_url)

    price = subscription.plan.price
    price_without_discount = (
        float(price) / (1 - subscription.promocode.discount / 100)
        if subscription.promocode
        else None
    )
    payment_form = PaymentForm()

    return render(
        request,
        'food_app/pages/checkout.html',
        {
            'payment_form': payment_form,
            'price': price,
            'price_without_discount': price_without_discount,
        },
    )


@csrf_exempt
@login_required
def payment_confirmation(request):
    payment_id = request.session.get('payment_id')
    subscription_id = request.session.get('subscription_id')

    # request.session.pop('payment_id', None)
    # request.session.pop('subscription_id', None)

    if not payment_id or not subscription_id:
        messages.error(request, 'Ошибка оплаты. Попробуйте, пожалуйста, снова.')
        return redirect('food_app:order')

    subscription = Subscription.objects.get(id=subscription_id)
    payment = Payment.find_one(payment_id)
    plan = subscription.plan

    if not subscription or not payment:
        messages.error(request, 'Ошибка оплаты. Попробуйте, пожалуйста, снова.')
        return redirect('food_app:order')

    if payment.status == 'succeeded':
        print(f'From views: {subscription}')
        subscription.is_active = True
        subscription.paid = True
        # subscription.save()
        subscription.save(update_fields=['is_active', 'paid'])

        # food_intakes = plan.food_intakes.all()

        # recipes = Recipe.objects.filter(
        #     category=plan.recipe_category,
        #     food_intake__in=food_intakes,
        # ).exclude(allergic_categories__in=plan.allergies.all())

        # menu_items = []
        # for food_intake in food_intakes:
        #
        #     current_date = subscription.start
        #     food_intake_recipes = recipes.filter(food_intake=food_intake).all()
        #
        #     while current_date <= subscription.end:
        #         menu_items.append(
        #             Menu(
        #                 date=current_date,
        #                 recipe=random.choice(food_intake_recipes),
        #                 subscription=subscription
        #             )
        #         )
        #
        # if menu_items:
        #     Menu.objects.bulk_create(menu_items)

        messages.success(request, 'Подписка успешно оформлена!')
        return redirect('food_app:account')

    messages.error(request, 'Ошибка оплаты. Попробуйте, пожалуйста, снова.')
    plan = subscription.plan
    plan.delete()
    subscription.delete()
    return redirect('food_app:order')


def get_plan_price(request):

    if not request.headers.get('X-Requested-With') == 'XMLHttpRequest':

food_app/templates/food_app/pages/auth.html
{% block title %} Вход {% endblock %}

{% block content %}
<main style="margin-top: calc(2rem + 85px);">
  <section>
      <div class="container">
          <div class="card p-3 mb-5 foodplan__shadow">
              <a href="{% url 'food_app:index' %}" class="link-secondary fw-light foodplan__backButton">
                  <svg xmlns="http://www.w3.org/2000/svg" width="9%" height="9%" fill="currentColor" class="bi bi-arrow-left-circle"
                      viewBox="0 0 16 16">
                      <path fill-rule="evenodd"
                          d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z" />
                  </svg>
              </a>
              <h2 class="text-center"><strong>Авторизация</strong></h2>
          </div>
          <div class="card px-5 py-3 d-flex align-items-center foodplan__shadow">
              <form method="post" action="{% url 'account_login' %}">
                  {% if form.errors %}
                    <ul class="alert alert-danger" role="alert">
                      {% for field, errors in form.errors.items %}
                        {% for error in errors %}
                          <li class="p-2" style="list-style-type: none;"><strong>{{ field.label }}</strong> {{ error }}</li>
                        {% endfor %}
                      {% endfor %}
                    </ul>
                  {% endif %}
                  {% csrf_token %}
                  <h1 class="mb-4 text-center"><strong>Вход</strong></h1>
                  <div class="mb-3">
                      <label for="exampleInputEmail1" class="form-label">Email</label>
                      <input name="{{ form.login.name }}" type="email" class="form-control" id="email" aria-describedby="emailHelp">
                  </div>
                  <div class="mb-3">
                      <div class="d-flex align-items-center justify-content-between">
                          <label for="exampleInputPassword1" class="form-label">Пароль</label>
                          <small><a href="{% url 'account_reset_password' %}" class="link-dark foodplan_green">Забыли пароль?</a></small>
                      </div>
                      <input name="{{ form.password.name }}" type="password" class="form-control" id="password">
                  </div>
                  <div class="row mb-3">
                      <div class="col-12 col-sm-6 mt-3">
                          <button type="submit"
                              class="btn w-100 btn-outline-success shadow-none foodplan_green foodplan__border_green">Войти</button>
                      </div>
                      <div class="col-12 col-sm-6 mt-3 d-flex justify-content-center align-items-center">
                          <small>Нет аккаунта? <a href="{% url 'account_signup' %}" class="link-dark foodplan_green">Зарегистрируйтесь</a></small>
                      </div>
                  </div>
              </form>
          </div>
      </div>
  </section>
</main>
{% endblock %}

food_app/templates/food_app/pages/checkout.html
{% extends 'food_app/base.html' %}

{% load static %}

{% block title %}Оплата{%endblock %}

{% block content %}
<main style="margin-top: calc(2rem + 85px)">
  <section>
    <div class="container">
      <div class="row">
        <div class="col-md-6 mx-auto my-5">
          <div class="card shadow p-5">
            <div class="card-header">
              <h1>Оплата</h1>
            </div>
            <div class="card-body">
              {% if payment_form.errors %}
                  <ul class="alert alert-danger" role="alert">
                      {% for field in payment_form %}
                          {% for error in field.errors %}
                              <li style="list-style-type: none;"><strong>{{ field.label }}:</strong> {{ error }}</li>
                          {% endfor %}
                      {% endfor %}
                  </ul>
              {% endif %}
              <form action="{% url 'food_app:checkout' %}" method="POST" id="payment-form" class="needs-validation">
                {% csrf_token %}
                <div class="form-group mb-2">
                  <label class="form-label" for="card-name">{{ payment_form.card_name.label }}</label>
                  {{ payment_form.card_name }}
                  <div class="invalid-feedback">
                    Введите, пожалуйста, корретное имя
                  </div>
                </div>
                <div class="form-group mb-2">
                  <label class="form-label" for="card-number">{{ payment_form.card_number.label }}</label>
                  {{ payment_form.card_number }}
                  <div class="invalid-feedback">
                    Пожалуйста, введите 16-значный номер карты, используя только цифры
                  </div>
                </div>
                <div class="form-group mb-2">
                  <label class="form-label" for="expiry-date">Срок действия</label>
                  <div class="row">
                    <div class="col-6">
                      {{ payment_form.card_month }}
                    </div>
                    <div class="col-6">
                      {{ payment_form.card_year }}
                    </div>
                  </div>
                  <div class="invalid-feedback">
                    Пожалуйста, введите дату истечения срока действия в формате MM/ГГ
                  </div>
                </div>
                <div class="form-group mb-4">
                  <label class="form-label" for="cvc">{{ payment_form.card_cvc.label }}</label>
                  {{ payment_form.card_cvc }}
                  <div class="invalid-feedback">
                    Введите 3-значный CVC, используя только цифры.
                  </div>
                </div>
                <button type="submit" class="btn btn-primary mt-3">
                  {% if price_without_discount %}
                    Оплатить: <span class="text-decoration-line-through  text-danger">{{price_without_discount}}</span> <span class="fw-bold">{{price}}р.</span>
                  {% else %}
                    Оплатить: {{price}} р.
                  {% endif %}
                </button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</main>
{% endblock %}

food_app/templates/food_app/pages/order.html
{% extends 'food_app/base.html' %} {% load static %} {% block title %}Личный
кабинет{% endblock %} {% block scripts %}
<script src="{% static 'food_app/js/calc_price.js' %}"></script>
{% endblock %} {% block content %}
<main style="margin-top: calc(2rem + 85px)">
  <section>
    <div class="container">
      <form id="order" action="{% url 'food_app:order' %}" method="POST">
        {% csrf_token %}

        <h1><strong class="foodplan_green">1 шаг </strong>до первого меню</h1>
        <h5 class="foodplan_green mb-3">Вам будет доступно 4 типа меню:</h5>

        {{ order_form.recipe_category }}

        <h2><strong>Выберите подходящий тариф</strong></h2>
        <table class="table text-center text-truncate mb-5">
          <div>
            {% if order_form.errors %}
              <ul class="alert alert-danger" role="alert">
                {% for field in order_form %} {% for error in field.errors %}
                <li style="list-style-type: none;"><strong>{{ field.label }}:</strong> {{ error }}</li>
                {% endfor %} {% endfor %}
              </ul>
            {% endif %}
          </div>
          <tbody>
            <tr>
              <th scope="row" class="text-start">Срок</th>
              <td>{{ order_form.period }}</td>
            </tr>
            <tr>
              <th scope="row" class="text-start">Кол-во персон</th>
              <td>{{ order_form.persons }}</td>
            </tr>
            <tr>
              <th scope="row" class="text-start">Приемы пищи</th>
              <td>
                {% for field in order_form.food_intakes %}
                <div class="form-check d-flex justify-content-start">
                  {{field}}
                </div>
                {% endfor %}
              </td>
            </tr>
            <tr>
              <th scope="row" class="text-start">Аллергии</th>
              <td>
                {% for field in order_form.allergies %}
                <div class="form-check d-flex justify-content-start">
                  {{field}}
                </div>
                {% endfor %}
              </td>
            </tr>
          </tbody>
        </table>
        <div
          class="card d-flex flex-row align-items-baseline mb-5 p-3 foodplan__bg_grey"
        >
          <div class='col-8'>
          {{ order_form.promo_code }}
          </div>
          <div class='col-2 text-center'>
          <button
            id="apply_promo"
            class="btn shadow-none btn-outline-success foodplan_green foodplan__border_green text-center"
          >
            Применить
          </button>
        </div>
          <div id="promo_alert" class="col-2">
            <div class="text-success" id="promo_success" style="display: none;">Применен</div>
            <div class="text-danger" id="promo_fail" style="display: none;">Недействителен</div>
          </div>
        </div>
        <div class="d-flex justify-content-center my-5">
          <button
            form="order"
            type="submit"
            class="btn shadow-none btn-outline-success foodplan_green foodplan__border_green w-50"
          >
            Оплатить
          </button>
        </div>
      </form>
    </div>
  </section>
</main>

{% endblock %}

food_app/templates/food_app/pages/registration.html
{% block title %} Вход {% endblock %}

{% block content %}
<main style="margin-top: calc(2rem + 85px);">
  <section>
      <div class="container">
          <div class="card p-3 mb-5 foodplan__shadow">
              <a href="#" class="link-secondary fw-light foodplan__backButton">
                  <svg xmlns="http://www.w3.org/2000/svg" width="9%" height="9%" fill="currentColor" class="bi bi-arrow-left-circle"
                      viewBox="0 0 16 16">
                      <path fill-rule="evenodd"
                          d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z" />
                  </svg>
              </a>
              <h2 class="text-center"><strong>Авторизация</strong></h2>
          </div>
          <div class="card px-5 py-3 d-flex align-items-center foodplan__shadow">
              <form method="post" action="{% url 'account_signup' %}">
                {% if form.errors %}
                  <ul class="alert alert-danger" role="alert">
                    {% for field, errors in form.errors.items %}
                      {% for error in errors %}
                        <li class="p-2" style="list-style-type: none;"><strong>{{ field.label }}</strong> {{ error }}</li>
                      {% endfor %}
                    {% endfor %}
                  </ul>
                {% endif %}
                  {% csrf_token %}
                  <h1 class="mb-4 text-center"><strong>Регистрация</strong></h1>
                  <div class="mb-3">
                      <label for="exampleInputEmail1" class="form-label">Никнейм</label>
                      <input name="{{ form.username.name }}" type="text" class="form-control" id="name">
                  </div>
                  <div class="mb-3">
                      <label for="exampleInputEmail1" class="form-label">Email</label>
                      <input name="{{ form.email.name }}" type="email" class="form-control" id="email" aria-describedby="emailHelp">
                  </div>
                  <div class="mb-3">
                      <label for="exampleInputPassword1" class="form-label">Пароль</label>
                      <input name="{{ form.password1.name }}" type="password" class="form-control" id="password">
                  </div>
                  <div class="mb-3">
                      <label for="exampleInputPassword1" class="form-label">Подтверждение пароля</label>
                      <input name="{{ form.password2.name }}" type="password" class="form-control" id="PasswordConfirm">
                  </div>
                  <div class="row mb-3">
                      <div class="col-12 col-sm-6 mt-3">
                          <button type="submit" class="btn  shadow-nonew-100 btn-outline-success foodplan_green foodplan__border_green">Регистрация</button>
                      </div>
                      <div class="col-12 col-sm-6 mt-3 d-flex justify-content-center align-items-center">
                          <small>Уже есть аккаунт? <a href="/accounts/login" class="link-dark foodplan_green">Войти</a></small>
                      </div>
                  </div>
              </form>
          </div>
      </div>
  </section>
</main>
{% endblock %}